### ISSUE TITLE
Documentation needs minor update

### ISSUE THREAD

**Issue by mbrouillet** [asus-linux-drivers/asus-wmi-hotkeys-driver#3]
On the project page https://github.com/asus-linux-drivers/asus-wmi-hotkeys-driver is displayed the README.md which intructs 
`git clone https://github.com/asus-wmi-hotkeys-driver/asus-wmi-hotkeys-driver`
This leads to 
```
Username for 'https://github.com': mbrouillet
Password for 'https://mbrouillet@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/asus-wmi-hotkeys-driver/asus-wmi-hotkeys-driver/'

```
I believe it should be replaced by what I copied under the green button CODE
```
git clone https://github.com/asus-linux-drivers/asus-wmi-hotkeys-driver.git
cd asus-wmi-hotkeys-driver/
```
It did work for me, but my model (UX582LR) is not an offered choice and to be honest I'm not sure what WMI hotkeys are. (I was hoping this would help get asus-touchpad-numpad-driver to work)

**Comment by ldrahnik** [comment]
@mbrouillet 

Hello there, thank you for creating an issue, the link has been updated.

This is separated driver and has nothing to do with NumberPad driver. What does this driver do? Remap Fn+special keys (the top line of keys on keyboard) to key combination `left shift + windows button + N/Q/T/R`. Why? Because direct mapping of Fn+key is not allowed, now can be used for shortcuts with scripts like disabling microphone/touchpad/camera/ ..

If any problem during installing/using driver NumberPad occurs, please create issue there. Try the latest master, it should work.
