### ISSUE TITLE
ux8402 keybindings

### ISSUE THREAD

**Issue by wormyrocks** [asus-linux-drivers/asus-wmi-hotkeys-driver#4]
FYI: testing this on ux8402, want to rebind the two additional keys above the touchpad on the top right. 
[Picture](https://mezha.media/wp-content/uploads/2022/11/ASUS-Zenbook-Pro-14-Duo-OLED-16.jpg)
In windows, one is "switch window to other screen" and the other is "screenpad disable".
Keycodes are:
```
KEY_WMI_SCREENPAD = 0x6A #106
KEY_WMI_SWITCHWINDOWS = 0x9C #156
```
Not submitting a pull request because I don't want to pollute the main repo with my own keybindings, but in case you want to roll ux8402 into a future upgrade.
The other keycodes seemed to match up fine with the existing ones in up541ea.
Cheers, thanks for this.

**Comment by ldrahnik** [comment]
Hello there,
thank you for creating an issue at first.

I know the driver is not designed well atm, was written more as an example of how can be the problem of not working special keys solved for my laptop than the well-configurable middle-man driver for easy rebinding all keys (Asus included) - until it will be fixed in the kernel. I guess should be better to have mentioned Asus's special key values in Readme.MD available for rebinding (in case they correspond across Asus laptops as I think they could, thanks for your confirmation) and template how config file has to looks like with example of mine / yours for example. Config file do not create by default and do not remove config file during reinstalling driver (I mean install script, uninstall script, ask if contains any changes). Backup of conf file with rebindings during reinstalling laptop let on the user.

Let me know what you think. I would appreciate any idea on how to design this driver clearly. And maybe exist already programmed solutions / tools for rebinding, in this case, I would appreciate a link to tools that can do this if you know. Then would be enough mention Asus keys in Readme.MD file and remove entire driver code or keep him but redesigned as I described above and mention links to other tools as similar solutions as well with quick example how to use them if necessary.

Btw about screen pad, do works in linux? Can you do please attach video in that case? I am open start writting driver for it if not but at this moment I have no laptop with screen pad. And also this is first time I see "mini" screen pad (I mean on the right), might be better for some kind of applications and I think it is better then central type.

Btw second display works in linux well?

I am open let you do any PR / contribution if you want. Let me know.

**Comment by ldrahnik** [comment]
The redesigned driver as mentioned above.

**Comment by ldrahnik** [comment]
@wormyrocks Can be reopened. I would appreciate continuing the discussion.

**Comment by wormyrocks** [comment]
Hi, yeah happy to continue discussion. The small trackpad is not a screen, but the bottom display works ok. I am currently using KDE Neon.
The full UX8402 looks like [this](https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSTj1a9BzEfZZg3NBHvsjGm0pfls62G-PpZM9ziAs05i6al987w_9Y8UV2DFIWRhCEgGTT3MEehkGpbzF_2tkceRklrOb-5Hpno-IE), it's quite a crazy machine. 
Folks have written about using it under Linux [here](https://davejansen.com/asus-zenbook-duo-and-fedora-linux/), and [here](https://www.reddit.com/r/linuxhardware/comments/snc61y/asus_zenbook_duo_14_and_fedora_linux/). And an existing kernel driver for some of the Screenpad / WMI reports is [here](https://github.com/Plippo/asus-wmi-screenpad). Maybe you could model a new version of your code after that? I am also not a linux expert but the machine is perfectly usable for me right now. 
There's also a [Screenpad discord](https://disboard.org/server/693135696080273408) where many folks are using Linux although it's not very active.

I think your driver is nice as is, clear and easy to understand. But definitely agree it could be cleaner in the future. It's been very useful to add a middle click function to my touchpad, as the remappable button sits right above the touchpad and the touchpad is too narrow to easily perform a three finger tap. It's functionality that I wish was present on Windows.
For the screenpad the most annoying issue right now is automatic mapping of touch devices to displays (which has been a problem with X for at least 10 years, with several partial solutions available.)
